apiVersion: v1
kind: Service
metadata:
  name: rcrr1
  labels:
    app: rcrr1
spec:
  selector:
    app: rcrr1
    tier: web
  ports:
  - port: 80
    targetPort: 4567
  type: LoadBalancer
  loadBalancerIP: 35.193.160.210
